### PR TITLE
HEC-983: get and delete test only endpoints

### PR DESCRIPTION
**Pull request by AndyHWChung**

### CODE REVIEW

**Review by LokeshSrinivasa — APPROVED** [review]

**Review by tinachou09 — APPROVED** [review]

**Comment by meghana-viswanath** [comment]
If these are purely for testing purposes, then would it useful to put them in a separate service?

**Comment by AndyHWChung** [comment]
having it separate is cleaner and more secure as well cos there's much less chance of accidentally deploying these kind of endpoints in prod. Having access to the actual code is useful sometimes just so that things like data structures and the like don't get out of sync. But also for this particular endpoint, we're talking to mongo and the platform doesn't like different microservices accessing the same mongo collections - I'll find a confluence link and share when I find it. But it basically refers back to the same kind of thing of data structures getting out of sync and avoiding tight coupling of microservices.

**Comment by meghana-viswanath** [comment]
Thanks for sharing the link about the [shared database anti-pattern](https://confluence.tools.tax.service.gov.uk/display/AR/Shared+Database) @AndyHWChung 

I understand concerns about coupling two microservices, but we'll be using this new service only for testing and so it'll never go to production. So might not be an issue in this situation?

**Comment by AndyHWChung** [comment]
I still think we'd still end up with syncing issues with the data models in particular. They're gonna be changing quite a few times I expect before we go to production and every time we do an update we'd need to remember to update case classes in multiple places which is extra effort. With these being test-only endpoints, we want to try to minimise the time needed to maintain them.

On the security side of things, as long as we remember to stick in `test-only` in the URL's we should be safe from the test only endpoints being made available in prod since there are rules written into NGINX to block requests to them.

**Comment by meghana-viswanath** [comment]
Yeah, that all makes sense to me. Maintaining data models across services is definitely a pain.

**Review by meghana-viswanath — APPROVED** [review]

**Pull request merged**
